### ISSUE TITLE
The dataset in not available

### ISSUE THREAD

**Issue by zhangabner** [53X/CogniNET#4]
The dataset can be found here :  https://drive.google.com/drive/folders/1k8qm560BYlybynB2YU9dj_kB4ZqrohfE

there only two ipynbs, which show the dataset is filepath = '/media/ayan/Drive/CVPR/DIstillation/Code/datasets/eeg_matlab'

could you share it?

**Comment by 53X** [comment]
Sorry for the late reply. Will share the dataset soon enough . Is it cool @zhangabner ?

**Comment by 53X** [comment]
The dataset is the one released in [this paper](https://arxiv.org/pdf/1609.00344.pdf). You can get the link to the dataset here. It is easier to download that way.
